spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:bibbidi;MODE=MySQL;DB_CLOSE_DELAY=-1;IGNORECASE=TRUE
    username: sa
    password: ""

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop

  sql:
    init:
      mode: always
      data-locations:
        - classpath:load_catalog.sql
        - classpath:load_terms.sql
