spring:
  datasource:
    url: ${BIBBIDI_DB_URL}
    username: ${BIBBIDI_DB_USERNAME}
    password: ${BIBBIDI_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: false

  sql:
    init:
      mode: never
